### ISSUE TITLE
User-can-search-any-movie-by-name

### ISSUE THREAD

**Issue by adrianm-arias** [adrianm-arias/ajax-project#1]
## 💰 Motivation

This enables the user to access a database of movies to look up more information of a particular movie they want to watch or know more about.

## 📐 Plan

Create a responsive layout that connects to an api, which then crawls the data from the api to match any keywords received from input, and returns any matches.

## 🖼️ Wireframes
![ajax-project-wireframe-issue-1](https://user-images.githubusercontent.com/104106959/182262701-4561540a-5e30-4b8b-9525-889f47cb1d7c.png)

## ✅ Task List

- [x] Create nav bar with logo and search nav link
- [x] Add a `div[data-view="search-form"]` to the HTML.
- [x] Create form with search input
  - [x] Capture input values from search input
  - [x] Listen for 'submit' events on search form
    - [x] Hide search input form once submit event occurs.
  - [x] Reset search input text
- [x] Create footer with logo and form with search input
- [x]  Retrieve data from api (themoviedv.org)
  - [x]  Parse json data into JavaScript object
  - [x] Return movie objects with match keyboard from search input
- [x] Verify correct data is being added to DOM tree from api
- [x] Verify nav bar stays on top when scrolling
- [x] Verify search results clear once new search query has been submitted
- [x] Verify both search input's work the same
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Verify layout is displaying correctly for mobile and desktop
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
